name: Run Dagger pipeline to train, then test model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    name: Run Dagger pipeline to train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.5
          cache: false

      - name: Run Dagger pipeline
        uses: dagger/dagger-for-github@v8.2.0
        with:
          workdir: .
          verb: run
          args: go run pipeline.go
          version: "0.19.6"

      - name: Relocate and rename model
        run: cp data/interim/lead_model.pkl artifacts/model.pkl #double check the original model location/name is correct

      - name: Upload Model Artifact #sourced from https://github.com/lasselundstenjensen/itu-sdse-project-model-validator
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: artifacts/model.pkl

  test: 
    name: Test Model using provided test
    needs: train
    runs on: ubuntu-latest

    steps:
      - name: Run Model Inference Test Action #copied from https://github.com/lasselundstenjensen/itu-sdse-project-model-validator
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
